In [2]:
"""

정수로 인코딩된 텍스트(시퀀스) 데이터셋이 embedding층을 통과했을 때 산출되는 결과 확인

"""

from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import Flatten
import numpy as np

# 정수로 인코딩된 텍스트(시퀀스) 데이터 3개로 데이터셋이 구성되어 있음

test = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])

# embedding층 생성(input_dim : int > 0. Size of the vocabulary.[i.e. maximum integer index + 1])
#                (output_dim: int >= 0. Dimension of the dense embedding)
#                (input_length: Length of input sequences, when it is constant. This argument is required if you are going to connect `Flatten` then `Dense` layers upstream
#                               Without it, the shape of the dense outputs cannot be computed.)

embedding = Embedding(13, 2)

# embedding층을 통과한 결과(embedding층을 통과한 결과값은 3차원 텐서임)

original_output = embedding(test)
print("* original_output :", "\n")
print(original_output, "\n")

# flatten layer를 통해, 3차원 텐서인 결과를 2차원 텐서로 변환

flatten = Flatten()
flatten_output = flatten(original_output)
print("* flatten_output :", "\n")
print(flatten_output)

* original_output : 

tf.Tensor(
[[[ 0.0049236   0.00380645]
  [ 0.0027077  -0.03027818]
  [-0.03935673 -0.03903745]
  [-0.03765916 -0.02912518]]

 [[-0.0015741   0.00748192]
  [ 0.02376603  0.04883314]
  [ 0.01615869 -0.03428886]
  [ 0.00277382 -0.03266327]]

 [[ 0.02027892 -0.00235651]
  [ 0.03397136  0.02884101]
  [ 0.02667049  0.01160431]
  [-0.02868512  0.03512588]]], shape=(3, 4, 2), dtype=float32) 

* flatten_output : 

tf.Tensor(
[[ 0.0049236   0.00380645  0.0027077  -0.03027818 -0.03935673 -0.03903745
  -0.03765916 -0.02912518]
 [-0.0015741   0.00748192  0.02376603  0.04883314  0.01615869 -0.03428886
   0.00277382 -0.03266327]
 [ 0.02027892 -0.00235651  0.03397136  0.02884101  0.02667049  0.01160431
  -0.02868512  0.03512588]], shape=(3, 8), dtype=float32)
