In [1]:
# 정수로 인코딩된 텍스트 데이터셋이 embedding층을 통과한 결과
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import Flatten

# 정수로 인코딩된 텍스트 데이터 3개로 해당 데이터셋이 구성되어 있음
test = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])

# embedding층 생성(매개변수를 통해 해당 embedding층에 대한 옵션 설정, input_length 매개변수에 설정은 안해도 상관없음)
embedding = Embedding(13, 2)

# embedding층을 통과한 결과(embedding층을 통과한 결과값은 3차원 텐서임)
'''한 개의 시퀀스 데이터(문장 데이터)가 embedding층을 통과하면, 해당 데이터의 차원이 '1'증가한다.'''
output = embedding(test)
print(output, "\n")

# 3차원 텐서인 결과를 2차원 텐서로 변환
flatten = Flatten()
output = flatten(output)
print(output)

tf.Tensor(
[[[-0.00543956  0.02127636]
  [ 0.03446132  0.00584198]
  [-0.04237906 -0.01965702]
  [ 0.03600531  0.00647569]]

 [[ 0.03990679  0.0405543 ]
  [-0.01339278  0.00545176]
  [ 0.03798331  0.00092264]
  [-0.01626499  0.04669598]]

 [[ 0.03265002  0.00802789]
  [-0.02623963  0.01893989]
  [ 0.02173693  0.01000526]
  [ 0.0358379   0.04017143]]], shape=(3, 4, 2), dtype=float32) 

tf.Tensor(
[[-0.00543956  0.02127636  0.03446132  0.00584198 -0.04237906 -0.01965702
   0.03600531  0.00647569]
 [ 0.03990679  0.0405543  -0.01339278  0.00545176  0.03798331  0.00092264
  -0.01626499  0.04669598]
 [ 0.03265002  0.00802789 -0.02623963  0.01893989  0.02173693  0.01000526
   0.0358379   0.04017143]], shape=(3, 8), dtype=float32)
